// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S2CProto.proto

package protobuf.proto.iharu;

/**
 * Protobuf enum {@code org.iharu.protobuf.AuthorityType}
 */
public enum AuthorityType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNDEFINED = 0;</code>
   */
  UNDEFINED(0),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNDEFINED = 0;</code>
   */
  public static final int UNDEFINED_VALUE = 0;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AuthorityType valueOf(int value) {
    return forNumber(value);
  }

  public static AuthorityType forNumber(int value) {
    switch (value) {
      case 0: return UNDEFINED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AuthorityType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AuthorityType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AuthorityType>() {
          public AuthorityType findValueByNumber(int number) {
            return AuthorityType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return protobuf.proto.iharu.S2CProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final AuthorityType[] VALUES = values();

  public static AuthorityType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AuthorityType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:org.iharu.protobuf.AuthorityType)
}

