// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: C2SProto.proto

package protobuf.proto.iharu;

public interface C2S_LoginProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.iharu.protobuf.C2S_LoginProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>int64 timestamp = 3;</code>
   */
  long getTimestamp();

  /**
   * <code>string inet = 4;</code>
   */
  java.lang.String getInet();
  /**
   * <code>string inet = 4;</code>
   */
  com.google.protobuf.ByteString
      getInetBytes();

  /**
   * <code>string macaddr = 5;</code>
   */
  java.lang.String getMacaddr();
  /**
   * <code>string macaddr = 5;</code>
   */
  com.google.protobuf.ByteString
      getMacaddrBytes();

  /**
   * <code>bytes config = 6;</code>
   */
  com.google.protobuf.ByteString getConfig();
}
