// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: C2SProto.proto

package protobuf.proto.iharu;

public interface C2S_SSOProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.iharu.protobuf.C2S_SSOProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>string voucher = 2;</code>
   */
  java.lang.String getVoucher();
  /**
   * <code>string voucher = 2;</code>
   */
  com.google.protobuf.ByteString
      getVoucherBytes();

  /**
   * <code>bytes term = 3;</code>
   */
  com.google.protobuf.ByteString getTerm();

  /**
   * <code>bytes payload = 4;</code>
   */
  com.google.protobuf.ByteString getPayload();

  /**
   * <code>int64 timestamp = 5;</code>
   */
  long getTimestamp();

  /**
   * <code>string inet = 6;</code>
   */
  java.lang.String getInet();
  /**
   * <code>string inet = 6;</code>
   */
  com.google.protobuf.ByteString
      getInetBytes();

  /**
   * <code>string macaddr = 7;</code>
   */
  java.lang.String getMacaddr();
  /**
   * <code>string macaddr = 7;</code>
   */
  com.google.protobuf.ByteString
      getMacaddrBytes();

  /**
   * <code>bytes config = 8;</code>
   */
  com.google.protobuf.ByteString getConfig();
}
