// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebResponseWrapper.proto

package protobuf.proto.iharu;

/**
 * Protobuf type {@code org.iharu.protobuf.HandshakeProto}
 */
public  final class HandshakeProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.iharu.protobuf.HandshakeProto)
    HandshakeProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HandshakeProto.newBuilder() to construct.
  private HandshakeProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HandshakeProto() {
    pk_ = com.google.protobuf.ByteString.EMPTY;
    token_ = com.google.protobuf.ByteString.EMPTY;
    config_ = com.google.protobuf.ByteString.EMPTY;
    sign_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HandshakeProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            pk_ = input.readBytes();
            break;
          }
          case 18: {

            token_ = input.readBytes();
            break;
          }
          case 26: {

            config_ = input.readBytes();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            sign_ = s;
            break;
          }
          case 40: {

            timestamp_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protobuf.proto.iharu.WebResponse.internal_static_org_iharu_protobuf_HandshakeProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protobuf.proto.iharu.WebResponse.internal_static_org_iharu_protobuf_HandshakeProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protobuf.proto.iharu.HandshakeProto.class, protobuf.proto.iharu.HandshakeProto.Builder.class);
  }

  public static final int PK_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString pk_;
  /**
   * <code>bytes pk = 1;</code>
   */
  public com.google.protobuf.ByteString getPk() {
    return pk_;
  }

  public static final int TOKEN_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString token_;
  /**
   * <pre>
   *for stateless server
   * </pre>
   *
   * <code>bytes token = 2;</code>
   */
  public com.google.protobuf.ByteString getToken() {
    return token_;
  }

  public static final int CONFIG_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString config_;
  /**
   * <code>bytes config = 3;</code>
   */
  public com.google.protobuf.ByteString getConfig() {
    return config_;
  }

  public static final int SIGN_FIELD_NUMBER = 4;
  private volatile java.lang.Object sign_;
  /**
   * <code>string sign = 4;</code>
   */
  public java.lang.String getSign() {
    java.lang.Object ref = sign_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sign_ = s;
      return s;
    }
  }
  /**
   * <code>string sign = 4;</code>
   */
  public com.google.protobuf.ByteString
      getSignBytes() {
    java.lang.Object ref = sign_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sign_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 5;
  private long timestamp_;
  /**
   * <code>int64 timestamp = 5;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!pk_.isEmpty()) {
      output.writeBytes(1, pk_);
    }
    if (!token_.isEmpty()) {
      output.writeBytes(2, token_);
    }
    if (!config_.isEmpty()) {
      output.writeBytes(3, config_);
    }
    if (!getSignBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sign_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(5, timestamp_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!pk_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, pk_);
    }
    if (!token_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, token_);
    }
    if (!config_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, config_);
    }
    if (!getSignBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sign_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, timestamp_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protobuf.proto.iharu.HandshakeProto)) {
      return super.equals(obj);
    }
    protobuf.proto.iharu.HandshakeProto other = (protobuf.proto.iharu.HandshakeProto) obj;

    if (!getPk()
        .equals(other.getPk())) return false;
    if (!getToken()
        .equals(other.getToken())) return false;
    if (!getConfig()
        .equals(other.getConfig())) return false;
    if (!getSign()
        .equals(other.getSign())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PK_FIELD_NUMBER;
    hash = (53 * hash) + getPk().hashCode();
    hash = (37 * hash) + TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getToken().hashCode();
    hash = (37 * hash) + CONFIG_FIELD_NUMBER;
    hash = (53 * hash) + getConfig().hashCode();
    hash = (37 * hash) + SIGN_FIELD_NUMBER;
    hash = (53 * hash) + getSign().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protobuf.proto.iharu.HandshakeProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.proto.iharu.HandshakeProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.proto.iharu.HandshakeProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.proto.iharu.HandshakeProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.proto.iharu.HandshakeProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.proto.iharu.HandshakeProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.proto.iharu.HandshakeProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.proto.iharu.HandshakeProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.proto.iharu.HandshakeProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protobuf.proto.iharu.HandshakeProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.proto.iharu.HandshakeProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.proto.iharu.HandshakeProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protobuf.proto.iharu.HandshakeProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.iharu.protobuf.HandshakeProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.iharu.protobuf.HandshakeProto)
      protobuf.proto.iharu.HandshakeProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.proto.iharu.WebResponse.internal_static_org_iharu_protobuf_HandshakeProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.proto.iharu.WebResponse.internal_static_org_iharu_protobuf_HandshakeProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.proto.iharu.HandshakeProto.class, protobuf.proto.iharu.HandshakeProto.Builder.class);
    }

    // Construct using protobuf.proto.iharu.HandshakeProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      pk_ = com.google.protobuf.ByteString.EMPTY;

      token_ = com.google.protobuf.ByteString.EMPTY;

      config_ = com.google.protobuf.ByteString.EMPTY;

      sign_ = "";

      timestamp_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protobuf.proto.iharu.WebResponse.internal_static_org_iharu_protobuf_HandshakeProto_descriptor;
    }

    @java.lang.Override
    public protobuf.proto.iharu.HandshakeProto getDefaultInstanceForType() {
      return protobuf.proto.iharu.HandshakeProto.getDefaultInstance();
    }

    @java.lang.Override
    public protobuf.proto.iharu.HandshakeProto build() {
      protobuf.proto.iharu.HandshakeProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protobuf.proto.iharu.HandshakeProto buildPartial() {
      protobuf.proto.iharu.HandshakeProto result = new protobuf.proto.iharu.HandshakeProto(this);
      result.pk_ = pk_;
      result.token_ = token_;
      result.config_ = config_;
      result.sign_ = sign_;
      result.timestamp_ = timestamp_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protobuf.proto.iharu.HandshakeProto) {
        return mergeFrom((protobuf.proto.iharu.HandshakeProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protobuf.proto.iharu.HandshakeProto other) {
      if (other == protobuf.proto.iharu.HandshakeProto.getDefaultInstance()) return this;
      if (other.getPk() != com.google.protobuf.ByteString.EMPTY) {
        setPk(other.getPk());
      }
      if (other.getToken() != com.google.protobuf.ByteString.EMPTY) {
        setToken(other.getToken());
      }
      if (other.getConfig() != com.google.protobuf.ByteString.EMPTY) {
        setConfig(other.getConfig());
      }
      if (!other.getSign().isEmpty()) {
        sign_ = other.sign_;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protobuf.proto.iharu.HandshakeProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protobuf.proto.iharu.HandshakeProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString pk_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes pk = 1;</code>
     */
    public com.google.protobuf.ByteString getPk() {
      return pk_;
    }
    /**
     * <code>bytes pk = 1;</code>
     */
    public Builder setPk(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pk_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes pk = 1;</code>
     */
    public Builder clearPk() {
      
      pk_ = getDefaultInstance().getPk();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString token_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     *for stateless server
     * </pre>
     *
     * <code>bytes token = 2;</code>
     */
    public com.google.protobuf.ByteString getToken() {
      return token_;
    }
    /**
     * <pre>
     *for stateless server
     * </pre>
     *
     * <code>bytes token = 2;</code>
     */
    public Builder setToken(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      token_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *for stateless server
     * </pre>
     *
     * <code>bytes token = 2;</code>
     */
    public Builder clearToken() {
      
      token_ = getDefaultInstance().getToken();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString config_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes config = 3;</code>
     */
    public com.google.protobuf.ByteString getConfig() {
      return config_;
    }
    /**
     * <code>bytes config = 3;</code>
     */
    public Builder setConfig(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      config_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes config = 3;</code>
     */
    public Builder clearConfig() {
      
      config_ = getDefaultInstance().getConfig();
      onChanged();
      return this;
    }

    private java.lang.Object sign_ = "";
    /**
     * <code>string sign = 4;</code>
     */
    public java.lang.String getSign() {
      java.lang.Object ref = sign_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sign_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sign = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSignBytes() {
      java.lang.Object ref = sign_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sign = 4;</code>
     */
    public Builder setSign(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sign_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sign = 4;</code>
     */
    public Builder clearSign() {
      
      sign_ = getDefaultInstance().getSign();
      onChanged();
      return this;
    }
    /**
     * <code>string sign = 4;</code>
     */
    public Builder setSignBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sign_ = value;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 5;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 5;</code>
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 5;</code>
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.iharu.protobuf.HandshakeProto)
  }

  // @@protoc_insertion_point(class_scope:org.iharu.protobuf.HandshakeProto)
  private static final protobuf.proto.iharu.HandshakeProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protobuf.proto.iharu.HandshakeProto();
  }

  public static protobuf.proto.iharu.HandshakeProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HandshakeProto>
      PARSER = new com.google.protobuf.AbstractParser<HandshakeProto>() {
    @java.lang.Override
    public HandshakeProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HandshakeProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HandshakeProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HandshakeProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protobuf.proto.iharu.HandshakeProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

