// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebResponseWrapper.proto

package protobuf.proto.iharu;

public interface HandshakeProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.iharu.protobuf.HandshakeProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes pk = 1;</code>
   */
  com.google.protobuf.ByteString getPk();

  /**
   * <pre>
   *for stateless server
   * </pre>
   *
   * <code>bytes token = 2;</code>
   */
  com.google.protobuf.ByteString getToken();

  /**
   * <code>bytes config = 3;</code>
   */
  com.google.protobuf.ByteString getConfig();

  /**
   * <code>string sign = 4;</code>
   */
  java.lang.String getSign();
  /**
   * <code>string sign = 4;</code>
   */
  com.google.protobuf.ByteString
      getSignBytes();

  /**
   * <code>int64 timestamp = 5;</code>
   */
  long getTimestamp();
}
