// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S2CProto.proto

package protobuf.proto.iharu;

public interface S2C_LoginProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.iharu.protobuf.S2C_LoginProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>bytes token = 2;</code>
   */
  com.google.protobuf.ByteString getToken();

  /**
   * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
   */
  java.util.List<protobuf.proto.iharu.S2C_LoginProto.Authorization> 
      getAuthList();
  /**
   * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
   */
  protobuf.proto.iharu.S2C_LoginProto.Authorization getAuth(int index);
  /**
   * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
   */
  int getAuthCount();
  /**
   * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
   */
  java.util.List<? extends protobuf.proto.iharu.S2C_LoginProto.AuthorizationOrBuilder> 
      getAuthOrBuilderList();
  /**
   * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
   */
  protobuf.proto.iharu.S2C_LoginProto.AuthorizationOrBuilder getAuthOrBuilder(
      int index);

  /**
   * <code>bytes config = 4;</code>
   */
  com.google.protobuf.ByteString getConfig();
}
