// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S2CProto.proto

package protobuf.proto.iharu;

/**
 * Protobuf type {@code org.iharu.protobuf.S2C_LoginProto}
 */
public  final class S2C_LoginProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.iharu.protobuf.S2C_LoginProto)
    S2C_LoginProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use S2C_LoginProto.newBuilder() to construct.
  private S2C_LoginProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private S2C_LoginProto() {
    username_ = "";
    token_ = com.google.protobuf.ByteString.EMPTY;
    auth_ = java.util.Collections.emptyList();
    config_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private S2C_LoginProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            username_ = s;
            break;
          }
          case 18: {

            token_ = input.readBytes();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              auth_ = new java.util.ArrayList<protobuf.proto.iharu.S2C_LoginProto.Authorization>();
              mutable_bitField0_ |= 0x00000004;
            }
            auth_.add(
                input.readMessage(protobuf.proto.iharu.S2C_LoginProto.Authorization.parser(), extensionRegistry));
            break;
          }
          case 34: {

            config_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        auth_ = java.util.Collections.unmodifiableList(auth_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protobuf.proto.iharu.S2CProto.internal_static_org_iharu_protobuf_S2C_LoginProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protobuf.proto.iharu.S2CProto.internal_static_org_iharu_protobuf_S2C_LoginProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protobuf.proto.iharu.S2C_LoginProto.class, protobuf.proto.iharu.S2C_LoginProto.Builder.class);
  }

  public interface AuthorizationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.iharu.protobuf.S2C_LoginProto.Authorization)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.org.iharu.protobuf.AuthorityType auth_type = 1;</code>
     */
    int getAuthTypeValue();
    /**
     * <code>.org.iharu.protobuf.AuthorityType auth_type = 1;</code>
     */
    protobuf.proto.iharu.AuthorityType getAuthType();

    /**
     * <code>int32 count = 2;</code>
     */
    int getCount();

    /**
     * <code>int64 expiry = 3;</code>
     */
    long getExpiry();

    /**
     * <code>int64 active = 4;</code>
     */
    long getActive();
  }
  /**
   * Protobuf type {@code org.iharu.protobuf.S2C_LoginProto.Authorization}
   */
  public  static final class Authorization extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.iharu.protobuf.S2C_LoginProto.Authorization)
      AuthorizationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Authorization.newBuilder() to construct.
    private Authorization(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Authorization() {
      authType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Authorization(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              authType_ = rawValue;
              break;
            }
            case 16: {

              count_ = input.readInt32();
              break;
            }
            case 24: {

              expiry_ = input.readInt64();
              break;
            }
            case 32: {

              active_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.proto.iharu.S2CProto.internal_static_org_iharu_protobuf_S2C_LoginProto_Authorization_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.proto.iharu.S2CProto.internal_static_org_iharu_protobuf_S2C_LoginProto_Authorization_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.proto.iharu.S2C_LoginProto.Authorization.class, protobuf.proto.iharu.S2C_LoginProto.Authorization.Builder.class);
    }

    public static final int AUTH_TYPE_FIELD_NUMBER = 1;
    private int authType_;
    /**
     * <code>.org.iharu.protobuf.AuthorityType auth_type = 1;</code>
     */
    public int getAuthTypeValue() {
      return authType_;
    }
    /**
     * <code>.org.iharu.protobuf.AuthorityType auth_type = 1;</code>
     */
    public protobuf.proto.iharu.AuthorityType getAuthType() {
      @SuppressWarnings("deprecation")
      protobuf.proto.iharu.AuthorityType result = protobuf.proto.iharu.AuthorityType.valueOf(authType_);
      return result == null ? protobuf.proto.iharu.AuthorityType.UNRECOGNIZED : result;
    }

    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_;
    /**
     * <code>int32 count = 2;</code>
     */
    public int getCount() {
      return count_;
    }

    public static final int EXPIRY_FIELD_NUMBER = 3;
    private long expiry_;
    /**
     * <code>int64 expiry = 3;</code>
     */
    public long getExpiry() {
      return expiry_;
    }

    public static final int ACTIVE_FIELD_NUMBER = 4;
    private long active_;
    /**
     * <code>int64 active = 4;</code>
     */
    public long getActive() {
      return active_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (authType_ != protobuf.proto.iharu.AuthorityType.UNDEFINED.getNumber()) {
        output.writeEnum(1, authType_);
      }
      if (count_ != 0) {
        output.writeInt32(2, count_);
      }
      if (expiry_ != 0L) {
        output.writeInt64(3, expiry_);
      }
      if (active_ != 0L) {
        output.writeInt64(4, active_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (authType_ != protobuf.proto.iharu.AuthorityType.UNDEFINED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, authType_);
      }
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, count_);
      }
      if (expiry_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, expiry_);
      }
      if (active_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, active_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.proto.iharu.S2C_LoginProto.Authorization)) {
        return super.equals(obj);
      }
      protobuf.proto.iharu.S2C_LoginProto.Authorization other = (protobuf.proto.iharu.S2C_LoginProto.Authorization) obj;

      if (authType_ != other.authType_) return false;
      if (getCount()
          != other.getCount()) return false;
      if (getExpiry()
          != other.getExpiry()) return false;
      if (getActive()
          != other.getActive()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AUTH_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + authType_;
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCount();
      hash = (37 * hash) + EXPIRY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExpiry());
      hash = (37 * hash) + ACTIVE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getActive());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.proto.iharu.S2C_LoginProto.Authorization parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.proto.iharu.S2C_LoginProto.Authorization parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.proto.iharu.S2C_LoginProto.Authorization parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.proto.iharu.S2C_LoginProto.Authorization parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.proto.iharu.S2C_LoginProto.Authorization parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.proto.iharu.S2C_LoginProto.Authorization parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.proto.iharu.S2C_LoginProto.Authorization parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.proto.iharu.S2C_LoginProto.Authorization parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.proto.iharu.S2C_LoginProto.Authorization parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.proto.iharu.S2C_LoginProto.Authorization parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.proto.iharu.S2C_LoginProto.Authorization parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.proto.iharu.S2C_LoginProto.Authorization parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.proto.iharu.S2C_LoginProto.Authorization prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.iharu.protobuf.S2C_LoginProto.Authorization}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.iharu.protobuf.S2C_LoginProto.Authorization)
        protobuf.proto.iharu.S2C_LoginProto.AuthorizationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.proto.iharu.S2CProto.internal_static_org_iharu_protobuf_S2C_LoginProto_Authorization_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.proto.iharu.S2CProto.internal_static_org_iharu_protobuf_S2C_LoginProto_Authorization_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.proto.iharu.S2C_LoginProto.Authorization.class, protobuf.proto.iharu.S2C_LoginProto.Authorization.Builder.class);
      }

      // Construct using protobuf.proto.iharu.S2C_LoginProto.Authorization.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        authType_ = 0;

        count_ = 0;

        expiry_ = 0L;

        active_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.proto.iharu.S2CProto.internal_static_org_iharu_protobuf_S2C_LoginProto_Authorization_descriptor;
      }

      @java.lang.Override
      public protobuf.proto.iharu.S2C_LoginProto.Authorization getDefaultInstanceForType() {
        return protobuf.proto.iharu.S2C_LoginProto.Authorization.getDefaultInstance();
      }

      @java.lang.Override
      public protobuf.proto.iharu.S2C_LoginProto.Authorization build() {
        protobuf.proto.iharu.S2C_LoginProto.Authorization result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protobuf.proto.iharu.S2C_LoginProto.Authorization buildPartial() {
        protobuf.proto.iharu.S2C_LoginProto.Authorization result = new protobuf.proto.iharu.S2C_LoginProto.Authorization(this);
        result.authType_ = authType_;
        result.count_ = count_;
        result.expiry_ = expiry_;
        result.active_ = active_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.proto.iharu.S2C_LoginProto.Authorization) {
          return mergeFrom((protobuf.proto.iharu.S2C_LoginProto.Authorization)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.proto.iharu.S2C_LoginProto.Authorization other) {
        if (other == protobuf.proto.iharu.S2C_LoginProto.Authorization.getDefaultInstance()) return this;
        if (other.authType_ != 0) {
          setAuthTypeValue(other.getAuthTypeValue());
        }
        if (other.getCount() != 0) {
          setCount(other.getCount());
        }
        if (other.getExpiry() != 0L) {
          setExpiry(other.getExpiry());
        }
        if (other.getActive() != 0L) {
          setActive(other.getActive());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.proto.iharu.S2C_LoginProto.Authorization parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.proto.iharu.S2C_LoginProto.Authorization) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int authType_ = 0;
      /**
       * <code>.org.iharu.protobuf.AuthorityType auth_type = 1;</code>
       */
      public int getAuthTypeValue() {
        return authType_;
      }
      /**
       * <code>.org.iharu.protobuf.AuthorityType auth_type = 1;</code>
       */
      public Builder setAuthTypeValue(int value) {
        authType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.org.iharu.protobuf.AuthorityType auth_type = 1;</code>
       */
      public protobuf.proto.iharu.AuthorityType getAuthType() {
        @SuppressWarnings("deprecation")
        protobuf.proto.iharu.AuthorityType result = protobuf.proto.iharu.AuthorityType.valueOf(authType_);
        return result == null ? protobuf.proto.iharu.AuthorityType.UNRECOGNIZED : result;
      }
      /**
       * <code>.org.iharu.protobuf.AuthorityType auth_type = 1;</code>
       */
      public Builder setAuthType(protobuf.proto.iharu.AuthorityType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        authType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.org.iharu.protobuf.AuthorityType auth_type = 1;</code>
       */
      public Builder clearAuthType() {
        
        authType_ = 0;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <code>int32 count = 2;</code>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>int32 count = 2;</code>
       */
      public Builder setCount(int value) {
        
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 count = 2;</code>
       */
      public Builder clearCount() {
        
        count_ = 0;
        onChanged();
        return this;
      }

      private long expiry_ ;
      /**
       * <code>int64 expiry = 3;</code>
       */
      public long getExpiry() {
        return expiry_;
      }
      /**
       * <code>int64 expiry = 3;</code>
       */
      public Builder setExpiry(long value) {
        
        expiry_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 expiry = 3;</code>
       */
      public Builder clearExpiry() {
        
        expiry_ = 0L;
        onChanged();
        return this;
      }

      private long active_ ;
      /**
       * <code>int64 active = 4;</code>
       */
      public long getActive() {
        return active_;
      }
      /**
       * <code>int64 active = 4;</code>
       */
      public Builder setActive(long value) {
        
        active_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 active = 4;</code>
       */
      public Builder clearActive() {
        
        active_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.iharu.protobuf.S2C_LoginProto.Authorization)
    }

    // @@protoc_insertion_point(class_scope:org.iharu.protobuf.S2C_LoginProto.Authorization)
    private static final protobuf.proto.iharu.S2C_LoginProto.Authorization DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.proto.iharu.S2C_LoginProto.Authorization();
    }

    public static protobuf.proto.iharu.S2C_LoginProto.Authorization getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Authorization>
        PARSER = new com.google.protobuf.AbstractParser<Authorization>() {
      @java.lang.Override
      public Authorization parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Authorization(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Authorization> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Authorization> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protobuf.proto.iharu.S2C_LoginProto.Authorization getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int USERNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object username_;
  /**
   * <code>string username = 1;</code>
   */
  public java.lang.String getUsername() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <code>string username = 1;</code>
   */
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOKEN_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString token_;
  /**
   * <code>bytes token = 2;</code>
   */
  public com.google.protobuf.ByteString getToken() {
    return token_;
  }

  public static final int AUTH_FIELD_NUMBER = 3;
  private java.util.List<protobuf.proto.iharu.S2C_LoginProto.Authorization> auth_;
  /**
   * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
   */
  public java.util.List<protobuf.proto.iharu.S2C_LoginProto.Authorization> getAuthList() {
    return auth_;
  }
  /**
   * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
   */
  public java.util.List<? extends protobuf.proto.iharu.S2C_LoginProto.AuthorizationOrBuilder> 
      getAuthOrBuilderList() {
    return auth_;
  }
  /**
   * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
   */
  public int getAuthCount() {
    return auth_.size();
  }
  /**
   * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
   */
  public protobuf.proto.iharu.S2C_LoginProto.Authorization getAuth(int index) {
    return auth_.get(index);
  }
  /**
   * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
   */
  public protobuf.proto.iharu.S2C_LoginProto.AuthorizationOrBuilder getAuthOrBuilder(
      int index) {
    return auth_.get(index);
  }

  public static final int CONFIG_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString config_;
  /**
   * <code>bytes config = 4;</code>
   */
  public com.google.protobuf.ByteString getConfig() {
    return config_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUsernameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, username_);
    }
    if (!token_.isEmpty()) {
      output.writeBytes(2, token_);
    }
    for (int i = 0; i < auth_.size(); i++) {
      output.writeMessage(3, auth_.get(i));
    }
    if (!config_.isEmpty()) {
      output.writeBytes(4, config_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUsernameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, username_);
    }
    if (!token_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, token_);
    }
    for (int i = 0; i < auth_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, auth_.get(i));
    }
    if (!config_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, config_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protobuf.proto.iharu.S2C_LoginProto)) {
      return super.equals(obj);
    }
    protobuf.proto.iharu.S2C_LoginProto other = (protobuf.proto.iharu.S2C_LoginProto) obj;

    if (!getUsername()
        .equals(other.getUsername())) return false;
    if (!getToken()
        .equals(other.getToken())) return false;
    if (!getAuthList()
        .equals(other.getAuthList())) return false;
    if (!getConfig()
        .equals(other.getConfig())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    hash = (37 * hash) + TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getToken().hashCode();
    if (getAuthCount() > 0) {
      hash = (37 * hash) + AUTH_FIELD_NUMBER;
      hash = (53 * hash) + getAuthList().hashCode();
    }
    hash = (37 * hash) + CONFIG_FIELD_NUMBER;
    hash = (53 * hash) + getConfig().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protobuf.proto.iharu.S2C_LoginProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.proto.iharu.S2C_LoginProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.proto.iharu.S2C_LoginProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.proto.iharu.S2C_LoginProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.proto.iharu.S2C_LoginProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.proto.iharu.S2C_LoginProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.proto.iharu.S2C_LoginProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.proto.iharu.S2C_LoginProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.proto.iharu.S2C_LoginProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protobuf.proto.iharu.S2C_LoginProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.proto.iharu.S2C_LoginProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.proto.iharu.S2C_LoginProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protobuf.proto.iharu.S2C_LoginProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.iharu.protobuf.S2C_LoginProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.iharu.protobuf.S2C_LoginProto)
      protobuf.proto.iharu.S2C_LoginProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.proto.iharu.S2CProto.internal_static_org_iharu_protobuf_S2C_LoginProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.proto.iharu.S2CProto.internal_static_org_iharu_protobuf_S2C_LoginProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.proto.iharu.S2C_LoginProto.class, protobuf.proto.iharu.S2C_LoginProto.Builder.class);
    }

    // Construct using protobuf.proto.iharu.S2C_LoginProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAuthFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      username_ = "";

      token_ = com.google.protobuf.ByteString.EMPTY;

      if (authBuilder_ == null) {
        auth_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        authBuilder_.clear();
      }
      config_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protobuf.proto.iharu.S2CProto.internal_static_org_iharu_protobuf_S2C_LoginProto_descriptor;
    }

    @java.lang.Override
    public protobuf.proto.iharu.S2C_LoginProto getDefaultInstanceForType() {
      return protobuf.proto.iharu.S2C_LoginProto.getDefaultInstance();
    }

    @java.lang.Override
    public protobuf.proto.iharu.S2C_LoginProto build() {
      protobuf.proto.iharu.S2C_LoginProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protobuf.proto.iharu.S2C_LoginProto buildPartial() {
      protobuf.proto.iharu.S2C_LoginProto result = new protobuf.proto.iharu.S2C_LoginProto(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.username_ = username_;
      result.token_ = token_;
      if (authBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          auth_ = java.util.Collections.unmodifiableList(auth_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.auth_ = auth_;
      } else {
        result.auth_ = authBuilder_.build();
      }
      result.config_ = config_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protobuf.proto.iharu.S2C_LoginProto) {
        return mergeFrom((protobuf.proto.iharu.S2C_LoginProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protobuf.proto.iharu.S2C_LoginProto other) {
      if (other == protobuf.proto.iharu.S2C_LoginProto.getDefaultInstance()) return this;
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        onChanged();
      }
      if (other.getToken() != com.google.protobuf.ByteString.EMPTY) {
        setToken(other.getToken());
      }
      if (authBuilder_ == null) {
        if (!other.auth_.isEmpty()) {
          if (auth_.isEmpty()) {
            auth_ = other.auth_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureAuthIsMutable();
            auth_.addAll(other.auth_);
          }
          onChanged();
        }
      } else {
        if (!other.auth_.isEmpty()) {
          if (authBuilder_.isEmpty()) {
            authBuilder_.dispose();
            authBuilder_ = null;
            auth_ = other.auth_;
            bitField0_ = (bitField0_ & ~0x00000004);
            authBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAuthFieldBuilder() : null;
          } else {
            authBuilder_.addAllMessages(other.auth_);
          }
        }
      }
      if (other.getConfig() != com.google.protobuf.ByteString.EMPTY) {
        setConfig(other.getConfig());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protobuf.proto.iharu.S2C_LoginProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protobuf.proto.iharu.S2C_LoginProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object username_ = "";
    /**
     * <code>string username = 1;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string username = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string username = 1;</code>
     */
    public Builder setUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      username_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string username = 1;</code>
     */
    public Builder clearUsername() {
      
      username_ = getDefaultInstance().getUsername();
      onChanged();
      return this;
    }
    /**
     * <code>string username = 1;</code>
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      username_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString token_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes token = 2;</code>
     */
    public com.google.protobuf.ByteString getToken() {
      return token_;
    }
    /**
     * <code>bytes token = 2;</code>
     */
    public Builder setToken(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      token_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes token = 2;</code>
     */
    public Builder clearToken() {
      
      token_ = getDefaultInstance().getToken();
      onChanged();
      return this;
    }

    private java.util.List<protobuf.proto.iharu.S2C_LoginProto.Authorization> auth_ =
      java.util.Collections.emptyList();
    private void ensureAuthIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        auth_ = new java.util.ArrayList<protobuf.proto.iharu.S2C_LoginProto.Authorization>(auth_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.proto.iharu.S2C_LoginProto.Authorization, protobuf.proto.iharu.S2C_LoginProto.Authorization.Builder, protobuf.proto.iharu.S2C_LoginProto.AuthorizationOrBuilder> authBuilder_;

    /**
     * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
     */
    public java.util.List<protobuf.proto.iharu.S2C_LoginProto.Authorization> getAuthList() {
      if (authBuilder_ == null) {
        return java.util.Collections.unmodifiableList(auth_);
      } else {
        return authBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
     */
    public int getAuthCount() {
      if (authBuilder_ == null) {
        return auth_.size();
      } else {
        return authBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
     */
    public protobuf.proto.iharu.S2C_LoginProto.Authorization getAuth(int index) {
      if (authBuilder_ == null) {
        return auth_.get(index);
      } else {
        return authBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
     */
    public Builder setAuth(
        int index, protobuf.proto.iharu.S2C_LoginProto.Authorization value) {
      if (authBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAuthIsMutable();
        auth_.set(index, value);
        onChanged();
      } else {
        authBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
     */
    public Builder setAuth(
        int index, protobuf.proto.iharu.S2C_LoginProto.Authorization.Builder builderForValue) {
      if (authBuilder_ == null) {
        ensureAuthIsMutable();
        auth_.set(index, builderForValue.build());
        onChanged();
      } else {
        authBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
     */
    public Builder addAuth(protobuf.proto.iharu.S2C_LoginProto.Authorization value) {
      if (authBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAuthIsMutable();
        auth_.add(value);
        onChanged();
      } else {
        authBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
     */
    public Builder addAuth(
        int index, protobuf.proto.iharu.S2C_LoginProto.Authorization value) {
      if (authBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAuthIsMutable();
        auth_.add(index, value);
        onChanged();
      } else {
        authBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
     */
    public Builder addAuth(
        protobuf.proto.iharu.S2C_LoginProto.Authorization.Builder builderForValue) {
      if (authBuilder_ == null) {
        ensureAuthIsMutable();
        auth_.add(builderForValue.build());
        onChanged();
      } else {
        authBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
     */
    public Builder addAuth(
        int index, protobuf.proto.iharu.S2C_LoginProto.Authorization.Builder builderForValue) {
      if (authBuilder_ == null) {
        ensureAuthIsMutable();
        auth_.add(index, builderForValue.build());
        onChanged();
      } else {
        authBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
     */
    public Builder addAllAuth(
        java.lang.Iterable<? extends protobuf.proto.iharu.S2C_LoginProto.Authorization> values) {
      if (authBuilder_ == null) {
        ensureAuthIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, auth_);
        onChanged();
      } else {
        authBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
     */
    public Builder clearAuth() {
      if (authBuilder_ == null) {
        auth_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        authBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
     */
    public Builder removeAuth(int index) {
      if (authBuilder_ == null) {
        ensureAuthIsMutable();
        auth_.remove(index);
        onChanged();
      } else {
        authBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
     */
    public protobuf.proto.iharu.S2C_LoginProto.Authorization.Builder getAuthBuilder(
        int index) {
      return getAuthFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
     */
    public protobuf.proto.iharu.S2C_LoginProto.AuthorizationOrBuilder getAuthOrBuilder(
        int index) {
      if (authBuilder_ == null) {
        return auth_.get(index);  } else {
        return authBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
     */
    public java.util.List<? extends protobuf.proto.iharu.S2C_LoginProto.AuthorizationOrBuilder> 
         getAuthOrBuilderList() {
      if (authBuilder_ != null) {
        return authBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(auth_);
      }
    }
    /**
     * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
     */
    public protobuf.proto.iharu.S2C_LoginProto.Authorization.Builder addAuthBuilder() {
      return getAuthFieldBuilder().addBuilder(
          protobuf.proto.iharu.S2C_LoginProto.Authorization.getDefaultInstance());
    }
    /**
     * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
     */
    public protobuf.proto.iharu.S2C_LoginProto.Authorization.Builder addAuthBuilder(
        int index) {
      return getAuthFieldBuilder().addBuilder(
          index, protobuf.proto.iharu.S2C_LoginProto.Authorization.getDefaultInstance());
    }
    /**
     * <code>repeated .org.iharu.protobuf.S2C_LoginProto.Authorization auth = 3;</code>
     */
    public java.util.List<protobuf.proto.iharu.S2C_LoginProto.Authorization.Builder> 
         getAuthBuilderList() {
      return getAuthFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.proto.iharu.S2C_LoginProto.Authorization, protobuf.proto.iharu.S2C_LoginProto.Authorization.Builder, protobuf.proto.iharu.S2C_LoginProto.AuthorizationOrBuilder> 
        getAuthFieldBuilder() {
      if (authBuilder_ == null) {
        authBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protobuf.proto.iharu.S2C_LoginProto.Authorization, protobuf.proto.iharu.S2C_LoginProto.Authorization.Builder, protobuf.proto.iharu.S2C_LoginProto.AuthorizationOrBuilder>(
                auth_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        auth_ = null;
      }
      return authBuilder_;
    }

    private com.google.protobuf.ByteString config_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes config = 4;</code>
     */
    public com.google.protobuf.ByteString getConfig() {
      return config_;
    }
    /**
     * <code>bytes config = 4;</code>
     */
    public Builder setConfig(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      config_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes config = 4;</code>
     */
    public Builder clearConfig() {
      
      config_ = getDefaultInstance().getConfig();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.iharu.protobuf.S2C_LoginProto)
  }

  // @@protoc_insertion_point(class_scope:org.iharu.protobuf.S2C_LoginProto)
  private static final protobuf.proto.iharu.S2C_LoginProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protobuf.proto.iharu.S2C_LoginProto();
  }

  public static protobuf.proto.iharu.S2C_LoginProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<S2C_LoginProto>
      PARSER = new com.google.protobuf.AbstractParser<S2C_LoginProto>() {
    @java.lang.Override
    public S2C_LoginProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new S2C_LoginProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<S2C_LoginProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<S2C_LoginProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protobuf.proto.iharu.S2C_LoginProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

