// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S2CProto.proto

package protobuf.proto.iharu;

public interface S2C_SSOProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.iharu.protobuf.S2C_SSOProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string voucher = 1;</code>
   */
  java.lang.String getVoucher();
  /**
   * <code>string voucher = 1;</code>
   */
  com.google.protobuf.ByteString
      getVoucherBytes();

  /**
   * <code>bytes term = 2;</code>
   */
  com.google.protobuf.ByteString getTerm();

  /**
   * <code>bytes payload = 3;</code>
   */
  com.google.protobuf.ByteString getPayload();

  /**
   * <code>int64 expiry = 4;</code>
   */
  long getExpiry();

  /**
   * <code>bytes config = 5;</code>
   */
  com.google.protobuf.ByteString getConfig();
}
