// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S2CProto.proto

package protobuf.proto.iharu;

/**
 * Protobuf type {@code org.iharu.protobuf.S2C_SSOProto}
 */
public  final class S2C_SSOProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.iharu.protobuf.S2C_SSOProto)
    S2C_SSOProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use S2C_SSOProto.newBuilder() to construct.
  private S2C_SSOProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private S2C_SSOProto() {
    voucher_ = "";
    term_ = com.google.protobuf.ByteString.EMPTY;
    payload_ = com.google.protobuf.ByteString.EMPTY;
    config_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private S2C_SSOProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            voucher_ = s;
            break;
          }
          case 18: {

            term_ = input.readBytes();
            break;
          }
          case 26: {

            payload_ = input.readBytes();
            break;
          }
          case 32: {

            expiry_ = input.readInt64();
            break;
          }
          case 42: {

            config_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protobuf.proto.iharu.S2CProto.internal_static_org_iharu_protobuf_S2C_SSOProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protobuf.proto.iharu.S2CProto.internal_static_org_iharu_protobuf_S2C_SSOProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protobuf.proto.iharu.S2C_SSOProto.class, protobuf.proto.iharu.S2C_SSOProto.Builder.class);
  }

  public static final int VOUCHER_FIELD_NUMBER = 1;
  private volatile java.lang.Object voucher_;
  /**
   * <code>string voucher = 1;</code>
   */
  public java.lang.String getVoucher() {
    java.lang.Object ref = voucher_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      voucher_ = s;
      return s;
    }
  }
  /**
   * <code>string voucher = 1;</code>
   */
  public com.google.protobuf.ByteString
      getVoucherBytes() {
    java.lang.Object ref = voucher_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      voucher_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TERM_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString term_;
  /**
   * <code>bytes term = 2;</code>
   */
  public com.google.protobuf.ByteString getTerm() {
    return term_;
  }

  public static final int PAYLOAD_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString payload_;
  /**
   * <code>bytes payload = 3;</code>
   */
  public com.google.protobuf.ByteString getPayload() {
    return payload_;
  }

  public static final int EXPIRY_FIELD_NUMBER = 4;
  private long expiry_;
  /**
   * <code>int64 expiry = 4;</code>
   */
  public long getExpiry() {
    return expiry_;
  }

  public static final int CONFIG_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString config_;
  /**
   * <code>bytes config = 5;</code>
   */
  public com.google.protobuf.ByteString getConfig() {
    return config_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getVoucherBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, voucher_);
    }
    if (!term_.isEmpty()) {
      output.writeBytes(2, term_);
    }
    if (!payload_.isEmpty()) {
      output.writeBytes(3, payload_);
    }
    if (expiry_ != 0L) {
      output.writeInt64(4, expiry_);
    }
    if (!config_.isEmpty()) {
      output.writeBytes(5, config_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getVoucherBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, voucher_);
    }
    if (!term_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, term_);
    }
    if (!payload_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, payload_);
    }
    if (expiry_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, expiry_);
    }
    if (!config_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, config_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protobuf.proto.iharu.S2C_SSOProto)) {
      return super.equals(obj);
    }
    protobuf.proto.iharu.S2C_SSOProto other = (protobuf.proto.iharu.S2C_SSOProto) obj;

    if (!getVoucher()
        .equals(other.getVoucher())) return false;
    if (!getTerm()
        .equals(other.getTerm())) return false;
    if (!getPayload()
        .equals(other.getPayload())) return false;
    if (getExpiry()
        != other.getExpiry()) return false;
    if (!getConfig()
        .equals(other.getConfig())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VOUCHER_FIELD_NUMBER;
    hash = (53 * hash) + getVoucher().hashCode();
    hash = (37 * hash) + TERM_FIELD_NUMBER;
    hash = (53 * hash) + getTerm().hashCode();
    hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getPayload().hashCode();
    hash = (37 * hash) + EXPIRY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExpiry());
    hash = (37 * hash) + CONFIG_FIELD_NUMBER;
    hash = (53 * hash) + getConfig().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protobuf.proto.iharu.S2C_SSOProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.proto.iharu.S2C_SSOProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.proto.iharu.S2C_SSOProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.proto.iharu.S2C_SSOProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.proto.iharu.S2C_SSOProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.proto.iharu.S2C_SSOProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.proto.iharu.S2C_SSOProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.proto.iharu.S2C_SSOProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.proto.iharu.S2C_SSOProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protobuf.proto.iharu.S2C_SSOProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.proto.iharu.S2C_SSOProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.proto.iharu.S2C_SSOProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protobuf.proto.iharu.S2C_SSOProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.iharu.protobuf.S2C_SSOProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.iharu.protobuf.S2C_SSOProto)
      protobuf.proto.iharu.S2C_SSOProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.proto.iharu.S2CProto.internal_static_org_iharu_protobuf_S2C_SSOProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.proto.iharu.S2CProto.internal_static_org_iharu_protobuf_S2C_SSOProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.proto.iharu.S2C_SSOProto.class, protobuf.proto.iharu.S2C_SSOProto.Builder.class);
    }

    // Construct using protobuf.proto.iharu.S2C_SSOProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      voucher_ = "";

      term_ = com.google.protobuf.ByteString.EMPTY;

      payload_ = com.google.protobuf.ByteString.EMPTY;

      expiry_ = 0L;

      config_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protobuf.proto.iharu.S2CProto.internal_static_org_iharu_protobuf_S2C_SSOProto_descriptor;
    }

    @java.lang.Override
    public protobuf.proto.iharu.S2C_SSOProto getDefaultInstanceForType() {
      return protobuf.proto.iharu.S2C_SSOProto.getDefaultInstance();
    }

    @java.lang.Override
    public protobuf.proto.iharu.S2C_SSOProto build() {
      protobuf.proto.iharu.S2C_SSOProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protobuf.proto.iharu.S2C_SSOProto buildPartial() {
      protobuf.proto.iharu.S2C_SSOProto result = new protobuf.proto.iharu.S2C_SSOProto(this);
      result.voucher_ = voucher_;
      result.term_ = term_;
      result.payload_ = payload_;
      result.expiry_ = expiry_;
      result.config_ = config_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protobuf.proto.iharu.S2C_SSOProto) {
        return mergeFrom((protobuf.proto.iharu.S2C_SSOProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protobuf.proto.iharu.S2C_SSOProto other) {
      if (other == protobuf.proto.iharu.S2C_SSOProto.getDefaultInstance()) return this;
      if (!other.getVoucher().isEmpty()) {
        voucher_ = other.voucher_;
        onChanged();
      }
      if (other.getTerm() != com.google.protobuf.ByteString.EMPTY) {
        setTerm(other.getTerm());
      }
      if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
        setPayload(other.getPayload());
      }
      if (other.getExpiry() != 0L) {
        setExpiry(other.getExpiry());
      }
      if (other.getConfig() != com.google.protobuf.ByteString.EMPTY) {
        setConfig(other.getConfig());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protobuf.proto.iharu.S2C_SSOProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protobuf.proto.iharu.S2C_SSOProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object voucher_ = "";
    /**
     * <code>string voucher = 1;</code>
     */
    public java.lang.String getVoucher() {
      java.lang.Object ref = voucher_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        voucher_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string voucher = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVoucherBytes() {
      java.lang.Object ref = voucher_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        voucher_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string voucher = 1;</code>
     */
    public Builder setVoucher(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      voucher_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string voucher = 1;</code>
     */
    public Builder clearVoucher() {
      
      voucher_ = getDefaultInstance().getVoucher();
      onChanged();
      return this;
    }
    /**
     * <code>string voucher = 1;</code>
     */
    public Builder setVoucherBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      voucher_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString term_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes term = 2;</code>
     */
    public com.google.protobuf.ByteString getTerm() {
      return term_;
    }
    /**
     * <code>bytes term = 2;</code>
     */
    public Builder setTerm(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      term_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes term = 2;</code>
     */
    public Builder clearTerm() {
      
      term_ = getDefaultInstance().getTerm();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes payload = 3;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }
    /**
     * <code>bytes payload = 3;</code>
     */
    public Builder setPayload(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      payload_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes payload = 3;</code>
     */
    public Builder clearPayload() {
      
      payload_ = getDefaultInstance().getPayload();
      onChanged();
      return this;
    }

    private long expiry_ ;
    /**
     * <code>int64 expiry = 4;</code>
     */
    public long getExpiry() {
      return expiry_;
    }
    /**
     * <code>int64 expiry = 4;</code>
     */
    public Builder setExpiry(long value) {
      
      expiry_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 expiry = 4;</code>
     */
    public Builder clearExpiry() {
      
      expiry_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString config_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes config = 5;</code>
     */
    public com.google.protobuf.ByteString getConfig() {
      return config_;
    }
    /**
     * <code>bytes config = 5;</code>
     */
    public Builder setConfig(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      config_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes config = 5;</code>
     */
    public Builder clearConfig() {
      
      config_ = getDefaultInstance().getConfig();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.iharu.protobuf.S2C_SSOProto)
  }

  // @@protoc_insertion_point(class_scope:org.iharu.protobuf.S2C_SSOProto)
  private static final protobuf.proto.iharu.S2C_SSOProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protobuf.proto.iharu.S2C_SSOProto();
  }

  public static protobuf.proto.iharu.S2C_SSOProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<S2C_SSOProto>
      PARSER = new com.google.protobuf.AbstractParser<S2C_SSOProto>() {
    @java.lang.Override
    public S2C_SSOProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new S2C_SSOProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<S2C_SSOProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<S2C_SSOProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protobuf.proto.iharu.S2C_SSOProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

